name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend:
    name: Backend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install deps
        working-directory: backend
        run: npm ci
      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate
      - name: Build
        working-directory: backend
        run: npm run build

  frontend:
    name: Frontend lint & build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: project/package-lock.json
      - name: Install deps
        working-directory: project
        run: npm ci
      - name: Lint
        working-directory: project
        run: npm run lint
      - name: Build
        working-directory: project
        run: npm run build


